Repository romreign45/contrubute-in-code, pull requests merged in 2022-10, with the labels that each got.

#1 merge_sort.cpp
  C++/merge_sort.cpp
Labels: hactoberfest, hactoberfest-accepted

#2 insertion_sort.cpp
  C++/insertion_sort.cpp
Labels: hactoberfest, hactoberfest-accepted

#3 greater_number.cpp
  C++/greater_number.cpp
Labels: hactoberfest, hactoberfest-accepted

#4 Create Longest increasing subSequence
  Longest increasing subSequence
Labels: hactoberfest, hactoberfest-accepted

#6 Added Bubblesort
  C++/BubbleSort.cpp
  Contribution.md
Labels: Hacktoberfest, Hacktoberfest-accepted

#10 Create BinarySearch.cpp
  C++/BinarySearch.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#7 Valid Parentheses
  C++/Valid Parentheses
Labels: Hacktoberfest, Hacktoberfest-accepted

#9 Pyramid Transition Matrix
  C++/Pyramid Transition Matrix
Labels: Hacktoberfest, Hacktoberfest-accepted

#13 create lcm.cpp
  C++/lcm.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#16 Swap. c
  C/swapping.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#18 reverse_a_string.java
  Java/reverse_a_string.java
Labels: Hacktoberfest, Hacktoberfest-accepted, Good contribution

#19 Added DiceCombinations.cpp
  C++/DiceCombinations.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#21 Tower_of_hanoi.py
  python/Tower_of_hanoi.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#25 odd-even.py
  python/odd-even.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#28 armstrong_number.py
  python/armstrong_number.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#29 factorial. c
  C/factorial. c
Labels: Hacktoberfest, Hacktoberfest-accepted

#26 N-ary Tree Level Order Traversal.cpp
  C++/Moore's Voting Algorithms.cpp
  C++/N-ary Tree Level Order Traversal.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#30 Create binary_search.java
  Java/binary_search.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#22 Recursive C++ code for GCD
  C++/gcd_recursive.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#34 Create longest substring with repeating substring
  C++/longest substring with repeating substring
Labels: Hacktoberfest, Hacktoberfest-accepted

#33 Counting_sort.cpp
  counting_sort.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#61 Create Shortest Distance in a Binary Maze
  C++/Shortest Distance in a Binary Maze
Labels: Hacktoberfest, Hacktoberfest-accepted

#45 2darraysum.cpp
  C++/array-2d/2darraysum.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#57 MultiplyArray.c
  C/MultiplyArray.c
Labels: Hacktoberfest, Hacktoberfest-accepted

#64 fibonacci.c
  C/fibonacci.c
Labels: Hacktoberfest, Hacktoberfest-accepted, Good contribution

#65 calculator.java
  Java/calculator.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#66 tower_of_honai.java
  Java/tower_of_honai.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#67 palindrome.py
  python/palindrome.py
Labels: Hacktoberfest, Hacktoberfest-accepted

#68 Create maximum subarray sum
  C++/maximum subarray sum
Labels: Hacktoberfest, Hacktoberfest-accepted

#72 Create Sum of all numbers in a string
  Sum of all numbers in a string
Labels: Hacktoberfest, Hacktoberfest-accepted

#70 Create generate parenthesis
  C++/generate parenthesis
Labels: Hacktoberfest, Hacktoberfest-accepted

#71 Create Sum of string
  Sum of string
Labels: Hacktoberfest, Hacktoberfest-accepted

#77 Floyd Warshall Algorithm
  C++/Floyd_warshall.c
  C++/Floyd_warshall.cpp
  C++/Hamitonian.cpp
  C++/KNapsack.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#78 Strassen's algorithm
  C++/Strassen’s_Matrix.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted

#79 hashing_with_chaining.cpp
  C++/hashing_with_chaining.cpp
Labels: Hacktoberfest, Hacktoberfest-accepted
